Fix(data):query event doesn't print error message
edgexfoundry/edgex-go pull request #2739
Opened 2020-10-01 14:27 UTC by cloudxxx8

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [x] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [x] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2738

## What is the new behavior?
If the query error is errors.KindEntityDoesNotExist, the error log
should not be printed out because it is not a real error.
In the infrastructure layer, if the event doesn't exist when adding, the
error should not be returned.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

2020-10-01 20:23 UTC, lenny-intel requested changes

2020-10-01 20:23 UTC, lenny-intel commented on internal/core/data/v2/controller/http/event.go
> +		if errors.Kind(err) != errors.KindEntityDoesNotExist {
Add comment why need to do this.

2020-10-02 02:06 UTC, cloudxxx8 commented on internal/core/data/v2/controller/http/event.go
> +		if errors.Kind(err) != errors.KindEntityDoesNotExist {
added comment

2020-10-02 16:32 UTC, lenny-intel approved these changes
LGTM

2020-10-03 04:07 UTC, merged