build: add supporting files for conventional commits
edgexfoundry/edgex-go pull request #2760
Opened 2020-10-07 00:08 UTC by jpwhitemn

add semantic.yml and Contributing.md files; update PULL_REQUEST_TEMPLATE.md; all files to support conventional commits for all PRs to this repository

fixes: #2759
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit subject follows the [Conventional Commits spec](https://github.com/zeke/semantic-pull-requests)
- [x] The commit message follows the [EdgeX Contributor Guide](https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)
- [x] `make test` has completed successfully

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Build related changes
- [x] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?
repo does not support conventional commits spec

Issue Number: #2759 

## What is the new behavior?
repo supports conventional commits

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Are there any new imports or modules? If so, what are they used for and why?
none

## Are there any specific instructions or things that should be known prior to reviewing?
none

## Other information

2020-10-07 18:51 UTC, jpwhitemn commented
recheck

2020-10-07 21:58 UTC, lenny-intel requested changes

2020-10-07 21:58 UTC, lenny-intel commented on .github/Contributing.md
> +
Remove this block

2020-10-08 15:53 UTC, lenny-intel approved these changes

2020-10-08 15:53 UTC, lenny-intel commented
recheck

2020-10-08 17:27 UTC, merged