Issue 2834
edgexfoundry/edgex-go pull request #2836
Opened 2020-10-21 14:19 UTC by judehung

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## New Imports

- [ ] Yes
- [ ] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2020-10-22 05:31 UTC, judehung commented
rebased

2020-10-22 10:31 UTC, judehung commented
rebased

2020-10-22 11:00 UTC, judehung commented
recheck

2020-10-22 17:02 UTC, lenny-intel submitted a review, later dismissed
LGTM

2020-10-23 01:19 UTC, judehung commented
rebased

2020-10-23 07:40 UTC, cloudxxx8 requested changes

2020-10-23 07:40 UTC, cloudxxx8 commented on internal/core/data/v2/controller/http/event.go
> +		if errors.Kind(err) != errors.KindEntityDoesNotExist {
delete action should log error anyway

2020-10-23 08:29 UTC, judehung commented on internal/core/data/v2/controller/http/event.go
> +		if errors.Kind(err) != errors.KindEntityDoesNotExist {
updated.

2020-10-23 09:39 UTC, cloudxxx8 commented
recheck

2020-10-23 09:40 UTC, cloudxxx8 approved these changes
LGTM

2020-10-23 10:14 UTC, merged