fix(snap) update to use kong deb from bintray
edgexfoundry/edgex-go pull request #2848
Opened 2020-10-23 16:12 UTC by tonyespy

## PR Checklist
Please check if your PR fulfills the following requirements:

- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?

NA

## Issue Number:
NA

## What is the new behavior?
NA

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## New Imports

- [ ] Yes
- [X] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing? No

## Other information
This PR updates the edgexfoundry snap to use the kong debian packages published on bintray vs. building lua, luarocks, kong, and openresty as individual parts (some from source, some downloaded tarballs).

We've verified that kong comes up by default on both amd64 and arm64, and also run the blackbox-tests with security enabled, and found no regressions.

2020-10-23 16:42 UTC, anonymouse64 commented on snap/snapcraft.yaml
> +      snapcraftctl set-version ${PROJECT_VERSION}
perhaps also call out this and the postgresql change in the PR description too? and thanks for making those things specific, separate commits

2020-10-23 16:45 UTC, anonymouse64 requested changes
some code in the PR seems leftover from a debugging session?

2020-10-23 16:45 UTC, anonymouse64 commented on snap/snapcraft.yaml
> +    #  - "-*"
why this change? Won't this add all the go binaries back into the snap?

2020-10-23 16:45 UTC, lenny-intel reviewed
LGTM, but will let the Snap experts have final approval.
I did validate version of Kong is correct

2020-10-23 16:47 UTC, lenny-intel commented
At Tony, failing Semantic bot due to missing `:` after scope. Should be `fix(snap): update to use kong deb from bintray`

2020-10-23 20:11 UTC, tonyespy commented
@anonymouse64 @lenny-intel changes addressed, and re-pushed.

2020-10-23 21:25 UTC, lenny-intel submitted a review, later dismissed

2020-10-23 22:43 UTC, anonymouse64 commented
Well I built and tested this PR on amd64 on my focal desktop and everything is groovy :wink: but I haven't been able to build it on arm64 yet to see if it's all good on the pi, I will have to do that on Monday, but I think that is a necessary check that should be done before merging since this is supposed to fix arm64.

2020-10-23 22:43 UTC, anonymouse64 requested changes
see previous comment

2020-10-26 14:28 UTC, tonyespy commented
@anonymouse64 just a heads-up that @siggiskulason ran the blackbox tests with security enabled against this PR on his RPi4, and although there were a couple of assertion errors thought to be timing related, we're confident that this change works fine on arm64.

2020-10-26 16:38 UTC, anonymouse64 approved these changes
Tested on my arm64 rpi4 running uc18 and kong worked fine in my testing, so lgtm. :tada: 
thanks for figuring this out

2020-10-26 17:49 UTC, hutchic commented
I don't have a lot of knowledge about snaps but this seems sensible and who am I to complain about a ~200 line reduction 😆

2020-10-27 15:42 UTC, tonyespy commented
recheck

2020-10-27 16:17 UTC, lenny-intel approved these changes

2020-10-27 16:19 UTC, merged