ci: standardize dockerfiles
edgexfoundry/edgex-go pull request #2960
Opened 2020-12-17 19:33 UTC by ernestojeda

- [x] use alpine 3.12
- [x] common `apk add` where possible
- [x] update copyright header where possible

Signed-off-by: Ernesto Ojeda <ernesto.ojeda@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number: #2941 

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2020-12-17 21:03 UTC, lenny-intel requested changes

2020-12-17 23:35 UTC, ernestojeda commented on Dockerfile.build
> +COPY --from=docker:20.10.0 /usr/local/bin/docker /usr/local/bin/docker
nice catch. I will remove docker from this image.

2020-12-18 01:22 UTC, lenny-intel approved these changes

2020-12-18 01:23 UTC, lenny-intel commented
recheck

2020-12-21 06:31 UTC, cloudxxx8 requested changes

2020-12-21 06:31 UTC, cloudxxx8 commented on Dockerfile.build
> -# This will be needed to run `make raml_verify`
should we put --no-cahce in the `RUN apk add` command?

2020-12-21 06:31 UTC, cloudxxx8 commented on cmd/core-data/Dockerfile
> +RUN apk add --no-cache zeromq
should we put --update in the `RUN apk add` command?

2021-01-04 16:23 UTC, cloudxxx8 approved these changes
LGTM

2021-01-04 16:30 UTC, merged