feat(sma): implement v2 GET /metrics/{services} API
edgexfoundry/edgex-go pull request #3467
Opened 2021-05-13 09:21 UTC by hahattan

- support both `executor` and `direct-service` MetricsMechanism
- reuse Metrics interface with v2 model
- heavily leverage v1 executor code but simplify concurrent logic

Signed-off-by: Chris Hung <chris@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number: fix #3454

## What is the new behavior?
response if MetricsMechanism is `executor`:
```
{
  apiVersion: "v2",
  statusCode: 200,
  metrics: {
    edgex-core-data: {
      Success: true,
      executor: "docker",
      operation: "metrics",
      result: {
        cpuUsedPercent: 0.07,
        memoryUsed: 8642363,
        raw: {
          block_io: "135kB / 0B",
          cpu_perc: "0.07%",
          mem_perc: "0.41%",
          mem_usage: "8.242MiB / 1.94GiB",
          net_io: "2.89MB / 6.3MB",
          pids: "13"
        }
      },
      service: "edgex-core-data"
    }
  }
}
```

response if MetricsMechanism is `direct-service`:
```
{
  apiVersion: "v2",
  statusCode: 200,
  metrics: {
    edgex-core-data: {
      apiVersion: "v2",
      metrics: {
        memAlloc: 1924632,
        memFrees: 23593,
        memLiveObjects: 13231,
        memMallocs: 36824,
        memSys: 74466312,
        memTotalAlloc: 3583736,
        cpuBusyAvg: 0
      }
    }
  }
}
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-05-17 22:37 UTC, lenny-intel approved these changes
LGTM

2021-05-18 02:12 UTC, hahattan commented
rebased, `v2/controller/http/controller.go` change is only sorting imports, no new code is added.

2021-05-18 14:27 UTC, cloudxxx8 requested changes

2021-05-18 14:27 UTC, cloudxxx8 commented on internal/system/agent/v2/controller/http/controller.go
> +	services := strings.Split(vars["services"], ",")
"services" should be a constant, and reuse the CommaSeparator
https://github.com/edgexfoundry/go-mod-core-contracts/blob/2c76dd9b4bb8135d36e7dd88eb99c6fe0fcdb492/v2/constants.go#L171

2021-05-18 14:27 UTC, cloudxxx8 commented on internal/system/agent/v2/router.go
> +	r.HandleFunc(v2.ApiMetricsRoute+"/{services}", ac.GetMetrics).Methods(http.MethodGet)
add a route in contract just like
https://github.com/edgexfoundry/go-mod-core-contracts/blob/2c76dd9b4bb8135d36e7dd88eb99c6fe0fcdb492/v2/constants.go#L115

try to add all SMA routes into contract

2021-05-19 03:48 UTC, cloudxxx8 approved these changes
LGTM

2021-05-19 03:48 UTC, merged