feat(sma): implement v2 POST /operation API
edgexfoundry/edgex-go pull request #3501
Opened 2021-05-24 02:47 UTC by hahattan

Signed-off-by: Chris Hung <chris@iotechsys.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number: fix #3496 

## What is the new behavior?
example request body POSTing `/api/v2/operation`:
```
[
    {
        "apiVersion": "v2",
        "requestId": "2f6fe5e2-dd93-478c-a2ba-21642e42a5f5",
        "serviceName": "edgex-core-data",
        "action": "start"
    },
    {
        "apiVersion": "v2",
        "requestId": "998d70a3-7245-4735-b308-ebb9f448fb38",
        "serviceName": "edgex-core-command",
        "action": "start"
    }
]
```

example response:
```
207 Multi-Status
[
    {
        "apiVersion": "v2",
        "requestId": "998d70a3-7245-4735-b308-ebb9f448fb38",
        "statusCode": 200
    },
    {
        "apiVersion": "v2",
        "requestId": "2f6fe5e2-dd93-478c-a2ba-21642e42a5f5",
        "statusCode": 200
    }
]
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-05-24 03:24 UTC, hahattan commented
recheck

2021-05-24 17:40 UTC, lenny-intel commented
recheck

2021-05-25 03:56 UTC, cloudxxx8 submitted a review, later dismissed
LGTM

2021-05-25 16:33 UTC, lenny-intel requested changes

2021-05-25 16:33 UTC, lenny-intel commented on internal/system/agent/v2/application/executor/operation.go
> +// Do implements the Metrics interface to obtain metrics via executor for one or more services concurrently.
I don't think this comment correct, i.e. specific to metrics? Please re-word the comment.

2021-05-25 16:51 UTC, lenny-intel approved these changes
LGTM

2021-05-25 17:22 UTC, merged

2021-05-27 09:44 UTC, hahattan commented
@lenny-intel btw do you have any comment about what I said in 'Other Information' in the PR  ?

2021-05-28 21:07 UTC, lenny-intel commented
> are we planning to remove the `edgex-` prefix for container name as well ?
> The behavior in SMA is inconsistent:
> 
> * for API that relies on executor (e.g. `/operation`, `metrics/{services}`), you need to refer the service by its container name, which have `edgex-` prefix
> * for API which will trigger requested service's own API (e.g. `/configs/{services}`), you don't have to add `edgex-` prefix

We did not plan to make that change to the container names, but I do see the inconsistency that it creates.
@jpwhitemn , please add this to next weeks Core WG agenda, i.e. **Remove `edgex-` prefix from container names in compose files**

2021-06-07 03:45 UTC, hahattan commented
@lenny-intel do we have any decision about the container naming ?

2021-06-07 17:47 UTC, lenny-intel commented
> @lenny-intel do we have any decision about the container naming ?

No, we didn't discuss in Core WG. Will be sure to discuss this week.