feat: Configure Kuiper for secure message bus
edgexfoundry/edgex-go pull request #3537
Opened 2021-06-02 22:36 UTC by lenny-intel

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?
Kuiper doesn't have secure message bus credentials for Redis MessageBus

## Issue Number: #3520

## What is the new behavior?
When in secure mode and message bus is `redis`, write Kuiper config file with Redis credentials.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-06-02 23:00 UTC, jim-wang-intel requested changes
would suggest using golnag's text/template for this perfect case

2021-06-02 23:39 UTC, lenny-intel commented on internal/security/secretstore/secure-messagebus.go
> +
Done

2021-06-02 23:48 UTC, jim-wang-intel approved these changes
LGTM

2021-06-03 00:12 UTC, lenny-intel commented
recheck

2021-06-03 02:20 UTC, merged