build(snap): runtime updates
edgexfoundry/edgex-go pull request #3568
Opened 2021-06-14 19:37 UTC by tonyespy

This PR includes a number of snap runtime updates:

 - remove the consul `--client` start option to restrict consul to localhost
 - fixes a problem with kong shutdown
 - redis --> 6.2.4
 - kong --> 2.4.1
 - vault --> 1.7.1

## PR Checklist
Please check if your PR fulfills the following requirements:

- [NA] Tests for the changes have been added (for bug fixes / features)
- [NA] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number:

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [ ] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-06-15 21:19 UTC, lenny-intel requested changes
Need to sync 3rd party app versions with that used in docker. 
https://github.com/edgexfoundry/edgex-compose/blob/master/compose-builder/.env#L39-L46

2021-06-15 21:19 UTC, lenny-intel commented on snap/snapcraft.yaml
> +    source-tag: v1.7.1
Note we update to the patch versions in compose yesterday to pin them and this one is now `1.7.2`.
Here is the list of versions used in docker: https://github.com/edgexfoundry/edgex-compose/blob/master/compose-builder/.env#L39-L46

2021-06-15 23:25 UTC, lenny-intel submitted a review, later dismissed
LGTM

2021-06-15 23:30 UTC, lenny-intel submitted a review, later dismissed

2021-06-16 14:23 UTC, siggiskulason commented
LGTM

2021-06-16 16:03 UTC, lenny-intel approved these changes

2021-06-16 16:03 UTC, merged