feat(security)!: Deprecate oauth2 auth method
edgexfoundry/edgex-go pull request #3575
Opened 2021-06-16 20:23 UTC by bnevis-i

Deprecates oauth2 proxy auth method
in favor of stronger JWT-based auth method
by removing ability for secrets-config utility
to create OAuth2 users.

security-proxy-setup accidentally broke
OAuth2 functionality by installing a global
JWT auth handler intended to secure admin API
(can't have two global auth handlers because
both auth methods must pass, which is impossible.)

Comment rather than remove code in case
it needs to be added back in Jakarta
stabilization release, otherwise will be
removed permanently in both secrets-config
and proxy-setup.

Closes #3564

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?
When adding proxy users with oauth2 auth method, Kong proxy authentication broken
due to installation of two global auth handlers.

## Issue Number:
Closes #3564

## What is the new behavior?
Remove oauth2-based authentication.

## Does this PR introduce a breaking change?
- [x] Yes
- [ ] No

OAuth2 was the default in Edinburgh preview security release.
JWT has been the default since Fuji release.
OAuth2 has been supported as a JWT alternative since Fuji.

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-06-16 20:37 UTC, lenny-intel requested changes
Looks good, Please add comments to each file on why this code is commented out rather then removed.

2021-06-17 00:06 UTC, bnevis-i commented
> Looks good, Please add comments to each file on why this code is commented out rather then removed.

Comments added.

2021-06-17 00:07 UTC, lenny-intel approved these changes
LGTM

2021-06-17 00:13 UTC, jim-wang-intel approved these changes
LGTM

2021-06-17 00:35 UTC, merged