docs: add Changelog for Ireland release
edgexfoundry/edgex-go pull request #3591
Opened 2021-06-23 03:01 UTC by jpwhitemn

Signed-off-by: Jim White <jpwhite_mn@yahoo.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/master/.github/Contributing.md.

## What is the current behavior?

## Issue Number:

## What is the new behavior?
Added changelog for Ireland release

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## New Imports

- [ ] Yes
- [x] No

## Specific Instructions
Are there any specific instructions or things that should be known prior to reviewing?

## Other information

2021-06-23 18:55 UTC, jpwhitemn commented
recheck

2021-06-23 21:02 UTC, lenny-intel requested changes

2021-06-24 01:02 UTC, jpwhitemn commented on CHANGELOG.md
> +- **security:** Fix Redis start issue from [#2863](https://github.com/edgexfoundry/edgex-go/issues/2863) ([#3115](https://github.com/edgexfoundry/edgex-go/issues/3115)) ([#cb6997bb](https://github.co
this one has some lines overlapping with below move to refactor.  I moved to refactor.  Can change if you prefer to move to fixes.  Seemed more like refactor so put there.

2021-06-24 15:12 UTC, lenny-intel approved these changes
LGTM

2021-06-24 16:51 UTC, lenny-intel approved these changes

2021-06-24 18:24 UTC, merged