feat(all): Update multi instance response to have totalCount field
edgexfoundry/edgex-go pull request #3746
Opened 2021-10-07 16:02 UTC by judehung

This PR includes several commits to close #3691:
1. update multi-instance response DTO to use BaseWithTotalCountResponse, so that a new field totalCount will be included as response DTOs.
2. update controller layer codes to fill in totalCount when preparing Multi-instance response.
3. update application layer codes to retrieve totalCount of instances that satisfied with query criteria.
4. update DB layer codes to get the total count of instances.
5. update open-api docs to reflect such changes
6. up openapi doc version to 2.1.0

Signed-off-by: Jude Hung <jude@iotechsys.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) This PR also covers the revision of  openapi swagger doc
  <link to docs PR>

## Testing Instructions

This PR must work with https://github.com/edgexfoundry/go-mod-core-contracts/pull/670
1. Modify the edgex-go's go.mod to replace the core-contracts lib
2. Run core-data
3. Add events and query events or readings through follow APIs and the response will have a new totalCount field to indicate the total count of events or readings:
`GET /event/all` 
`GET /event/device/name/{name}`
`GET /event/start/{start}/end/{end}`
`GET /reading/all`
`GET /reading/device/name/{deviceName}/resourceName/{resourceName}`
`GET /reading/device/name/{deviceName}/resourceName/{resourceName}/start/{start}/end/{end}`
`GET /reading/device/name/{name}`
`GET /reading/resourceName/{resourceName}`
`GET /reading/resourceName/{resourceName}/start/{start}/end/{end}`
`GET /reading/start/{start}/end/{end}`
4. Run core-metadata
5. Run device-virtual to add devices/device profiles/device service into metadata, and then query devices/device profiles/device service through following APIs.  The response will have a new totalCount field to indicate the total count of devices/device profiles/device service:
`GET /device/all`
`GET /device/profile/name/{name}`
`GET /device/service/name/{name}`
`GET /deviceprofile/all`
`GET /deviceprofile/manufacturer/{manufacturer}`
`GET /deviceprofile/manufacturer/{manufacturer}/model/{model}`
`GET /deviceprofile/model/{model}`
`GET /deviceservice/all`
6. Add several provision watchers into core-metadata, and then query provision watchers through following APIs.  The response will have a new totalCount field to indicate the total count of provision watchers:
`GET /provisionwatcher/all`
`GET /provisionwatcher/service/name/{name}`
`GET /provisionwatcher/profile/name/{name}`
7. Run core-command
8. Query device core commands through following API, and the response will have a new totalCount field to indicate the total count of device core commands:
`GET /device/all`
9. Run support-scheduler
10. Add several Intervals and IntervalActions into support-scheduler, and then query Intervals and IntervalActions through following APIs.  The response will have a new totalCount field to indicate the total count of Intervals and IntervalActions:
`GET /interval/all`
`GET /intervalaction/all`
11. Run support-notification
12. Add several Subscriptions and Notifications into support-notifications, and then query Subscriptions, Notifications, and Transmissions through following APIs.  These responses will have a new totalCount field to indicate the total count of Subscriptions, Notifications, and Transmissions:
`/subscription/all`
`/subscription/category/{category}`
`/subscription/label/{label}`
`/subscription/receiver/{receiver}`
`/notification/start/{start}/end/{end}`
`/notification/category/{category}`
`/notification/label/{label}`
`/notification/status/{status}`
`/notification/subscription/name/{name}`
`/transmission/all`
`/transmission/status/{status}`
`/transmission/subscription/name/{name}`
`/transmission/start/{start}/end/{end}`

## New Dependency Instructions (If applicable)

2021-10-11 13:26 UTC, cloudxxx8 commented on internal/core/data/application/event.go
> +	totalCount, err = dbClient.EventTotalCount()
right, that's for the GUI to calculate the total pages and proper pagination

2021-10-18 02:27 UTC, cloudxxx8 approved these changes
LGTM

2021-10-18 21:51 UTC, lenny-intel requested changes

2021-10-18 21:51 UTC, lenny-intel commented on internal/core/data/application/event.go
> +	} else {
Remove `else` since not need due to above `return`.

2021-10-18 21:51 UTC, lenny-intel commented on internal/core/data/application/event.go
> +	} else {
Remove `else` since not need due to above `return`.
This is a repeated pattern. Please fix every it is used.

2021-10-18 21:51 UTC, lenny-intel commented on internal/core/data/application/reading.go
> +	} else {
Similar pattern. `else` not needed.

2021-10-19 05:34 UTC, judehung commented
@lenny-intel I've removed all those unnecessary else condition per yuor suggestion.  https://github.com/edgexfoundry/edgex-go/pull/3746/commits/07a5fd5fe76f5e37a3f246b752b337e7675b084c

2021-10-20 02:50 UTC, judehung commented
rebased and update go.mod/go.sum to pick up the latest version of go-mod-core-contracts.

2021-10-20 03:27 UTC, merged