ci: Go 1.17 related changes
edgexfoundry/edgex-go pull request #3864
Opened 2022-01-19 19:51 UTC by ernestojeda

Changes related to Go 1.17 and cache optimizations

2022-01-19 22:53 UTC, lenny-intel commented on cmd/support-scheduler/Dockerfile
> +ARG BUILDER_BASE=golang:1.17-alpine3.15
Other changes missing?

2022-01-19 23:42 UTC, lenny-intel requested changes
Also need to update go version used by snap here: https://github.com/edgexfoundry/edgex-go/blob/b0e5e643282aa8d6ca4ca25954737fd68a04a1f7/snap/snapcraft.yaml#L584

2022-01-19 23:47 UTC, lenny-intel approved these changes
LGTM

2022-01-19 23:50 UTC, lenny-intel approved these changes

2022-01-19 23:53 UTC, farshidtz requested changes

2022-01-19 23:53 UTC, farshidtz commented on snap/snapcraft.yaml
> +      - go/1.17/stable
This doesn't look right.

2022-01-19 23:54 UTC, farshidtz commented on snap/snapcraft.yaml
> +      - go/1.17/stable
I was too slow. It is already fixed..

2022-01-19 23:56 UTC, ernestojeda commented on snap/snapcraft.yaml
> +      - go/1.17/stable
yeah, had a bad find/replace. 🥺

2022-01-20 00:04 UTC, lenny-intel approved these changes
LGTM

2022-01-20 00:13 UTC, merged