build(snap): use edgex-ekuiper stage-snap
edgexfoundry/edgex-go pull request #3904
Opened 2022-03-15 09:29 UTC by MonicaisHer

- remove secure message bus setup as config files coming from edgex-ekuiper stage-snap directly
- use configure hook generating redis creds for kuiper
- update kuiper `apps` and `parts`

Signed-off-by: Mengyi Wang <mengyi.wang@canonical.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [ ] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-03-22 10:02 UTC, farshidtz requested changes

2022-03-22 10:02 UTC, farshidtz commented on snap/snapcraft.yaml
> +      CONNECTIONS_FILE: $SNAP_DATA/kuiper/etc/connections/connection.yaml
CONNECTIONS_FILE -> CONNECTION_FILE

2022-03-24 08:57 UTC, farshidtz commented on snap/local/hooks/cmd/install/install.go
> +
The edge-ekuiper snap sets `KuiperBaseKey: $SNAP_DATA` while this snap has it set to `KuiperBaseKey: $SNAP_DATA/kuiper`. As a result, an additional script is called here to copy them (why not move) to copy ./etc from former to latter directory.

Can't we just make the [install hook](https://github.com/canonical/edgex-ekuiper-snap/blob/main/snap/hooks/install) of edgex-ekuiper take an environment variable as input base path which is set to `$SNAP_DATA` by default and set to `$SNAP_DATA/kuiper` by passing [Cmd.Env](https://pkg.go.dev/os/exec#Cmd) when called here?

2022-03-25 16:37 UTC, farshidtz requested changes
Thanks @MonicaisHer. 
It looks good. Added a few minor comments.

2022-03-25 16:43 UTC, MonicaisHer commented on snap/local/hooks/cmd/install/install.go
> +	fmt.Println(fmt.Sprintf("edgexfoundry:install-kuiper: %s", stdoutStderr))
error is logged [here](https://github.com/edgexfoundry/edgex-go/blob/main/snap/local/hooks/cmd/install/install.go#L395)

2022-03-25 16:47 UTC, farshidtz commented on snap/local/hooks/cmd/install/install.go
> +	fmt.Println(fmt.Sprintf("edgexfoundry:install-kuiper: %s", stdoutStderr))
I meant that standard errors aren't logged. As far as I know, `err` doesn't include the standard errors.

2022-03-28 08:31 UTC, MonicaisHer commented on snap/snapcraft.yaml
> -      - -etc/services/
Do you mean to include files using the `-` prefix? `+` prefix doesn't work with `stage:`

2022-03-28 08:39 UTC, farshidtz commented on snap/snapcraft.yaml
> -      - -etc/services/
The `-` prefix is to exclude. No prefix means inclusion (not `+`). Not to be confused with the hyphen used in YAML list. See https://snapcraft.io/docs/snapcraft-filesets which has the same syntax.

Anyway, let's leave it for future work.

2022-04-04 14:47 UTC, farshidtz approved these changes

2022-04-04 14:48 UTC, merged