fix(metadata): not trigger DS callback if only lastConnected is updated
edgexfoundry/edgex-go pull request #3976
Opened 2022-04-18 05:47 UTC by hahattan

fix #3641

Signed-off-by: Chris Hung <chris@iotechsys.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?) n/a
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) n/a
  <link to docs PR>

## Testing Instructions

1. run metadata from this branch
2. run device-virtual with `DEBUG` log level
3. verify PATCH `/api/v2/deviceprofile` will not trigger DS callback if only updating `lastConnected` field

## New Dependency Instructions (If applicable)

2022-04-18 06:48 UTC, cloudxxx8 requested changes

2022-04-18 06:48 UTC, cloudxxx8 commented on internal/core/metadata/application/deviceservice.go
> +		dto.BaseAddress == nil && dto.AdminState == nil && len(dto.Labels) == 0 {
It's a good idea to not invoke callback if only lastConnected field is updated.
However, this if statement is hard to maintain if we add more fields into the Device struct.
Please write a helper function and use the reflect package to replace this if statement.
https://pkg.go.dev/reflect
Use a for loop to go through all the fields in this DTO and check the logic you designed.

2022-04-19 03:58 UTC, cloudxxx8 approved these changes
LGTM

2022-04-19 15:38 UTC, lenny-intel approved these changes
LGTM

2022-04-19 15:38 UTC, merged