feat(metadata): implement GET Units of Measure API
edgexfoundry/edgex-go pull request #4127
Opened 2022-08-17 08:33 UTC by hahattan

dependent on https://github.com/edgexfoundry/go-mod-core-contracts/pull/756

cbc81fb9b27178ac0d33edb17f9e140940e39377 updated `uom.toml` configuration structure in order to return similar content for json/toml response. 

fix #3957 

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?) N/A
  <link to docs PR>

## Testing Instructions

1. Run core-metadata from this branch
2. 
```shell
$ curl localhost:59881/api/v2/uom
{
    "apiVersion": "v2",
    "statusCode": 200,
    "uom": {
        "source": "reference to source for all UoM if not specified below",
        "units": {
            "temperature": {
                "source": "www.weather.com",
                "values": [
                    "C",
                    "F",
                    "K"
                ]
            },
            "weights": {
                "source": "www.usa.gov/federal-agencies/weights-and-measures-division",
                "values": [
                    "lbs",
                    "ounces",
                    "kilos",
                    "grams"
                ]
            }
        }
    }
}

$ curl -H "Accept: application/toml" localhost:59881/api/v2/uom
Source = "reference to source for all UoM if not specified below"

[Units]

  [Units.temperature]
    Source = "www.weather.com"
    Values = ["C", "F", "K"]

  [Units.weights]
    Source = "www.usa.gov/federal-agencies/weights-and-measures-division"
    Values = ["lbs", "ounces", "kilos", "grams"]
```

## New Dependency Instructions (If applicable)

2022-08-17 19:36 UTC, lenny-intel commented
@hahattan , I noticed the `I am not introducing a breaking change` isn't checked in the PR checklist above. I assume this was just missed and there are not breaking changes :-)

2022-08-17 19:50 UTC, lenny-intel requested changes

2022-08-17 19:50 UTC, lenny-intel commented on internal/core/metadata/controller/http/uom_test.go
> +				assert.Equal(t, http.StatusOK, recorder.Result().StatusCode, "HTTP status code not as expected")
This is common for both content types. Move out of if/else

2022-08-17 19:50 UTC, lenny-intel commented on internal/core/metadata/controller/http/uom_test.go
> +
add assert to verify actual actualResponse  equals expected response

2022-08-17 19:50 UTC, lenny-intel commented on internal/core/metadata/controller/http/uom_test.go
> +				assert.Equal(t, common.ApiVersion, actualResponse.ApiVersion, "Api Version not as expected")
add assert to verify actual actualResponse  equals expected response

2022-08-18 02:53 UTC, hahattan commented
> @hahattan , I noticed the `I am not introducing a breaking change` isn't checked in the PR checklist above. I assume this was just missed and there are not breaking changes :-)

not sure whether updating the `uom.toml` is a breaking change so I left it unchecked

2022-08-18 14:19 UTC, cloudxxx8 approved these changes
LGTM

2022-08-18 14:20 UTC, cloudxxx8 commented
> > @hahattan , I noticed the `I am not introducing a breaking change` isn't checked in the PR checklist above. I assume this was just missed and there are not breaking changes :-)
> 
> not sure whether updating the `uom.toml` is a breaking change so I left it unchecked

it's not a breaking change, because this file didn't exist in the previous release

2022-08-18 15:45 UTC, lenny-intel approved these changes
LGTM

2022-08-18 15:45 UTC, merged