feat(command): subscribe command request via internal messaging
edgexfoundry/edgex-go pull request #4177
Opened 2022-10-03 05:56 UTC by hahattan

core-command subscribes to internal command requests and publishes requests to the to the appropriate device service via messaging

Signed-off-by: Chris Hung <chris@iotechsys.com>

fix #4170

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

1. Run core-command from this branch with `MESSAGEQUEUE_REQUIRED=true` environment variable
2. Send command requests via `redis` container to InternalRequestCommandTopic, for example:
```shell
/data # redis-cli
127.0.0.1:6379> PUBLISH .command.request.Random-Boolean-Device.Bool.get '{"CorrelationID": "14a42ea6-c394-41c3-8bcd-a29b9f5e6835", "ApiVersion": "v2", "RequestId": "e6e8a2f4-eb14-4649-9e2b-175247911369", "Content-Type": "application/json"}'
(integer) 1
```
3. Verified core-command receives the request, propagates to device service, receives the response and send back to internal messaging (`redis` container) on InternalResponseCommandTopicPrefix topic:
```
level=DEBUG ts=2022-10-03T05:53:17.983273178Z app=core-command source=internal.go:107 msg="Command request received on message queue. Topic: /command/request/Random-Boolean-Device/Bool/get, Correlation-id: 14a42ea6-c394-41c3-8bcd-a29b9f5e6835 "
level=DEBUG ts=2022-10-03T05:53:17.987350115Z app=core-command source=internal.go:147 msg="Command request sent to message queue. Topic: edgex/command/request/device-virtual/Random-Boolean-Device/Bool/get, Correlation-id: 14a42ea6-c394-41c3-8bcd-a29b9f5e6835"
level=DEBUG ts=2022-10-03T05:53:17.987990896Z app=core-command source=internal.go:52 msg="Command response received on message queue. Topic: edgex/command/response/device-virtual/Random-Boolean-Device/Bool/get, Correlation-id: 14a42ea6-c394-41c3-8bcd-a29b9f5e6835 "
level=DEBUG ts=2022-10-03T05:53:17.988207693Z app=core-command source=internal.go:70 msg="Published response message on topic '/command/response/Random-Boolean-Device/Bool/get'"
```
`redis`:
```shell
/data # redis-cli
127.0.0.1:6379> PSUBSCRIBE .command.response.*
Reading messages... (press Ctrl-C to quit)
1) "psubscribe"
2) ".command.response.*"
3) (integer) 1
1) "pmessage"
2) ".command.response.*"
3) ".command.response.Random-Boolean-Device.Bool.get"
4) "{\"ReceivedTopic\":\"edgex/command/response/device-virtual/Random-Boolean-Device/Bool/get\",\"CorrelationID\":\"14a42ea6-c394-41c3-8bcd-a29b9f5e6835\",\"ApiVersion\":\"v2\",\"RequestID\":\"e6e8a2f4-eb14-4649-9e2b-175247911369\",\"ErrorCode\":0,\"Payload\":\"eyJhcGlWZXJzaW9uIjoidjIiLCJzdGF0dXNDb2RlIjoyMDAsImV2ZW50Ijp7ImFwaVZlcnNpb24iOiJ2MiIsImlkIjoiZmI3OWUwZWItMTBkYi00NWRjLTkzM2MtMGFjNjlmZjk0MzNjIiwiZGV2aWNlTmFtZSI6IlJhbmRvbS1Cb29sZWFuLURldmljZSIsInByb2ZpbGVOYW1lIjoiUmFuZG9tLUJvb2xlYW4tRGV2aWNlIiwic291cmNlTmFtZSI6IkJvb2wiLCJvcmlnaW4iOjE2NjQ3NzY0ODA1NTkwOTU1MjYsInJlYWRpbmdzIjpbeyJpZCI6Ijk4MjU5MWRlLTNlNDYtNGI0YS04Mjc5LTg2NDNkODVhYTM3MSIsIm9yaWdpbiI6MTY2NDc3NjQ4MDU1OTA5NTUyNiwiZGV2aWNlTmFtZSI6IlJhbmRvbS1Cb29sZWFuLURldmljZSIsInJlc291cmNlTmFtZSI6IkJvb2wiLCJwcm9maWxlTmFtZSI6IlJhbmRvbS1Cb29sZWFuLURldmljZSIsInZhbHVlVHlwZSI6IkJvb2wiLCJ2YWx1ZSI6InRydWUifV19fQ==\",\"ContentType\":\"application/json\",\"QueryParams\":{}}"

```

## New Dependency Instructions (If applicable)

2022-10-03 17:26 UTC, lenny-intel commented on internal/core/command/controller/messaging/internal.go
> +func SubscribeCommandRequests(ctx context.Context, router MessagingRouter, dic *di.Container) errors.EdgeX {
Add Godoc style comments for public functions.

2022-10-03 17:29 UTC, lenny-intel commented on internal/core/command/controller/messaging/internal.go
> +				internalRequestTopic, err := validateRequestTopic(messageBusInfo.Internal.Topics[RequestTopicPrefix], deviceName, commandName, method, dic)
```suggestion
				deviceRequestTopic, err := validateRequestTopic(messageBusInfo.Internal.Topics[RequestTopicPrefix], deviceName, commandName, method, dic)
```

2022-10-03 17:30 UTC, lenny-intel commented on internal/core/command/controller/messaging/internal.go
> +				err = messageBus.Publish(requestEnvelope, internalRequestTopic)
```suggestion
				err = messageBus.Publish(requestEnvelope, deviceRequestTopic)
```

2022-10-04 17:59 UTC, lenny-intel requested changes
One minor comment tweak needed, otherwise looks great!

2022-10-04 17:59 UTC, lenny-intel commented on internal/core/command/controller/messaging/internal.go
> +// SubscribeCommandRequests subscribes command requests from EdgeX service (e.g., Application Service)
Perfect!

2022-10-04 17:59 UTC, lenny-intel commented on internal/core/command/controller/messaging/router.go
> +	// DeviceResponseTopic returns the responseTopicPrefix by requestId, and a boolean value
I don't think you meant to change this one.
```suggestion
	// ResponseTopic returns the responseTopicPrefix by requestId, and a boolean value
```

2022-10-05 00:38 UTC, lenny-intel approved these changes
LGTM

2022-10-05 05:26 UTC, cloudxxx8 requested changes

2022-10-05 05:26 UTC, cloudxxx8 commented on cmd/core-command/res/configuration.toml
> +    ResponseQueryTopic = "/commandquery/response"   # for publishing reponsses back to internal service
according to your naming convention, you should either rename `RequestDeviceTopicPrefix` or `CommnadRequestTopic`

2022-10-05 06:23 UTC, cloudxxx8 approved these changes
LGTM

2022-10-05 06:25 UTC, merged