refactor(command): refactor messaging handler
edgexfoundry/edgex-go pull request #4204
Opened 2022-10-19 10:04 UTC by hahattan

- update external commandQueryHandler function signature
- remove duplicate error message

Signed-off-by: Chris Hung <chris@iotechsys.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2022-10-19 14:58 UTC, hahattan commented
recheck

2022-10-19 17:19 UTC, lenny-intel commented
Note that the snap build is currently failing on all PRs. Snap team is aware and says we can merge without it passing.

2022-10-19 17:23 UTC, lenny-intel requested changes

2022-10-19 17:23 UTC, lenny-intel commented on internal/core/command/controller/messaging/external.go
> +		responseTopic := messageBusInfo.External.Topics[QueryResponseTopic]
Do we need to verify `QueryResponseTopic` exists in `Topics`

2022-10-20 14:59 UTC, lenny-intel submitted a review, later dismissed
LGTM

2022-10-20 14:59 UTC, lenny-intel commented
@hahattan , some failed tests.

2022-10-22 17:53 UTC, lenny-intel approved these changes
LGTM

2022-10-22 17:54 UTC, merged