feat(wip): Create secret store tokens via identity auth
edgexfoundry/edgex-go pull request #4244
Opened 2022-12-03 04:38 UTC by bnevis-i

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [X] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2023-03-01 01:41 UTC, bnevis-i commented
@farshidtz Blocked by https://github.com/canonical/edgex-snap-testing/pull/163

2023-03-01 15:05 UTC, farshidtz commented
> @farshidtz To be unblocked by [canonical/edgex-snap-testing#163](https://github.com/canonical/edgex-snap-testing/pull/163)

Thanks, looking into it. But please keep in mind that the snap tests don't block PR merges.

2023-03-01 16:27 UTC, jim-wang-intel requested changes
some minor changes

2023-03-01 16:27 UTC, jim-wang-intel commented on internal/security/config/command/proxy/shared/proxyuser.go
> +// SPDX-License-Identifier: Apache-2.0'
```suggestion
// SPDX-License-Identifier: Apache-2.0
```

2023-03-01 16:27 UTC, jim-wang-intel commented on internal/security/config/command/proxy/shared/proxyuser.go
> +// NewVaultBase sets up everything needed to instantiate a SecretStoreClient
```suggestion
// NewProxyUserCommon sets up everything needed to instantiate a SecretStoreClient
```

2023-03-01 16:27 UTC, jim-wang-intel commented on internal/security/config/command/proxy/shared/proxyuser.go
> +// loadRootToken regenerates a temporary root token from Vault keyshares
```suggestion
// LoadRootToken regenerates a temporary root token from Vault keyshares
```

2023-03-02 04:06 UTC, bnevis-i commented on cmd/security-bootstrapper/entrypoint-scripts/nginx_wait_install.sh
> +# In particular, it waits for the security-bootstrapper's ReadyToRunPort and Postgres db ready to roll
fixed

2023-03-02 04:06 UTC, bnevis-i commented on cmd/security-bootstrapper/entrypoint-scripts/nginx_wait_install.sh
> +echo "Script for waiting security bootstrapping on Kong"
fixed.

2023-03-02 04:08 UTC, bnevis-i commented on cmd/security-bootstrapper/entrypoint-scripts/nginx_wait_install.sh
> +test -f /etc/nginx/templates/edgex-custom-rewrites.inc.template || cat <<'EOH' > /etc/nginx/templates/edgex-custom-rewrites.inc.template
fixed with long-form if..else

2023-03-02 04:09 UTC, bnevis-i commented on cmd/security-bootstrapper/entrypoint-scripts/proxy_setup_wait_install.sh
>    -uri tcp://"${STAGEGATE_BOOTSTRAPPER_HOST}":"${STAGEGATE_READY_TORUNPORT}" \
fixed comment above.

2023-03-02 04:09 UTC, bnevis-i commented on cmd/security-proxy-setup/Dockerfile
>        copyright='Copyright (c) 2019: Dell Technologies, Inc.'
added

2023-03-02 04:09 UTC, bnevis-i commented on internal/security/config/command/proxy/shared/proxyuser.go
> +// SPDX-License-Identifier: Apache-2.0'
fixed typo

2023-03-02 04:09 UTC, bnevis-i commented on internal/security/config/command/proxy/shared/proxyuser.go
> +// NewVaultBase sets up everything needed to instantiate a SecretStoreClient
fixed

2023-03-02 04:09 UTC, bnevis-i commented on internal/security/config/command/proxy/shared/proxyuser.go
> +// loadRootToken regenerates a temporary root token from Vault keyshares
fixed

2023-03-02 17:56 UTC, jim-wang-intel commented on internal/security/config/command/proxy/tls/command.go
>  // SPDX-License-Identifier: Apache-2.0'
just saw this:
```suggestion
// SPDX-License-Identifier: Apache-2.0
```

2023-03-02 17:56 UTC, jim-wang-intel commented on internal/security/config/bootstraphandler.go
>  // SPDX-License-Identifier: Apache-2.0'
just saw this:
```suggestion
// SPDX-License-Identifier: Apache-2.0
```

2023-03-02 17:56 UTC, jim-wang-intel commented on internal/security/config/command/help/command.go
>  // SPDX-License-Identifier: Apache-2.0'
just saw this:
```suggestion
// SPDX-License-Identifier: Apache-2.0
```

2023-03-02 17:56 UTC, jim-wang-intel commented on internal/security/config/command/proxy/adduser/command.go
>  // SPDX-License-Identifier: Apache-2.0'
just saw this:
```suggestion
// SPDX-License-Identifier: Apache-2.0
```

2023-03-02 17:56 UTC, jim-wang-intel commented on internal/security/config/command/proxy/command.go
>  // SPDX-License-Identifier: Apache-2.0'
sorry, just saw this:
```suggestion
// SPDX-License-Identifier: Apache-2.0
```

2023-03-02 17:56 UTC, jim-wang-intel commented on internal/security/config/command/proxy/deluser/command.go
>  // SPDX-License-Identifier: Apache-2.0'
```suggestion
// SPDX-License-Identifier: Apache-2.0
```

2023-03-02 22:07 UTC, bnevis-i commented on internal/security/config/command/proxy/tls/command.go
>  // SPDX-License-Identifier: Apache-2.0'
fixed in rebase

2023-03-02 22:07 UTC, bnevis-i commented on internal/security/config/bootstraphandler.go
>  // SPDX-License-Identifier: Apache-2.0'
fixed in rebase

2023-03-02 22:08 UTC, bnevis-i commented on internal/security/config/command/proxy/adduser/command.go
>  // SPDX-License-Identifier: Apache-2.0'
fixed in rebase

2023-03-02 22:09 UTC, bnevis-i commented on internal/security/config/command/help/command.go
>  // SPDX-License-Identifier: Apache-2.0'
fixed in rebase

2023-03-02 22:09 UTC, bnevis-i commented on internal/security/config/command/proxy/command.go
>  // SPDX-License-Identifier: Apache-2.0'
fixed in rebase

2023-03-02 22:09 UTC, bnevis-i commented on internal/security/config/command/proxy/deluser/command.go
>  // SPDX-License-Identifier: Apache-2.0'
fixed in rebase

2023-03-03 00:01 UTC, jim-wang-intel approved these changes
LGTM

2023-03-06 15:01 UTC, merged

2023-03-10 12:02 UTC, farshidtz reviewed
Already merged but I'd like to suggest making the CLI argument naming conventions consistent:

```
$ edgexfoundry.secrets-config proxy adduser -h
Usage of adduser:
  -configDir string
    	
  -jwtTTL string
    	JWT created by vault identity provider lasts this long (default "1h")
  -tokenTTL string
    	Vault token created as a result of vault login lasts this long (default "1h")
  -useRootToken
    	Set to true to TokenFile in config points to a resp-init.json instead of a service token
  -user string
    	Username of the user to add
level=ERROR ts=2023-03-10T11:55:04.114755814Z app=secrets-config source=bootstraphandler.go:70 msg="unable to parse command: -h: flag: help requested"
```
Ok - all camelCase

```
$ edgexfoundry.secrets-config proxy deluser -h
Usage of deluser:
  -configDir string
    	
  -useRootToken
    	Set to true to TokenFile in config points to a resp-init.json instead of a service token
  -user string
    	Username of the user to delete
level=ERROR ts=2023-03-10T11:55:10.795005034Z app=secrets-config source=bootstraphandler.go:70 msg="Unable to parse command: -h: flag: help requested"
```
Ok - all camelCase

```
$ edgexfoundry.secrets-config proxy tls -h
Usage of tls:
  -certfilename string
    	Filename of certificate file (on target) (default "nginx.crt")
  -configDir string
    	
  -incert string
    	Path to PEM-encoded leaf certificate
  -inkey string
    	Path to PEM-encoded private key
  -keyfilename string
    	Filename of private key file (on target (default "nginx.key")
  -targetfolder string
    	Path to TLS key file (default "/etc/ssl/nginx")
level=ERROR ts=2023-03-10T11:55:14.547332083Z app=secrets-config source=bootstraphandler.go:70 msg="unable to parse command: -h: flag: help requested"
```
Not OK.

- `-certfilename` -> `-certFilename`
- `-incert` -> `-inCert`
- `-inkey` -> `inKey`
- `-keyfilename` -> `-keyFilename`
- `-targetfolder` -> `-targetFolder`

Also, I don't know why it is printing error on `-h`.

@bnevis-i I'll open an issue if necessary.

2023-03-10 12:09 UTC, farshidtz commented
Related PRs:
- https://github.com/edgexfoundry/edgex-docs/pull/981
- https://github.com/edgexfoundry/edgex-compose/pull/345

2023-03-10 18:11 UTC, bnevis-i commented
@farshidtz  See #4433 for fixes described in https://github.com/edgexfoundry/edgex-go/pull/4244#pullrequestreview-1334725750