feat: Implement Provision Watcher System Events
edgexfoundry/edgex-go pull request #4346
Opened 2023-02-13 10:17 UTC by jinlinGuan

- publish system events for provision watcher add/update/delete
- remove the REST callbacks

close #4329

Signed-off-by: Ginny Guan <ginny@iotechsys.com>

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [x] I have opened a PR for the related docs change (if not, why?)
https://github.com/edgexfoundry/edgex-docs/pull/960

## Testing Instructions

1. build and run core-metadata with other services
2. find the correct logs
3. (optional) subscribe the redis messagebus system event topic and receive the correct messages

- add a provision watcher 
```
level=DEBUG ts=2023-02-13T09:48:21.487595056Z app=core-metadata source=provisionwatcher.go:37 msg="ProvisionWatcher created on DB successfully. ProvisionWatcher ID: 705136c5-6228-494a-8e27-f0946e1d2554, Correlation-ID: 71129ebb-344b-4799-96ec-150cd7028705 "
level=DEBUG ts=2023-02-13T09:48:21.488277751Z app=core-metadata source=notify.go:225 msg="Published the 'add' System Event for provisionwatcher 'provisionwatcher-1' to topic 'edgex/system-events/core-metadata/provisionwatcher/add/device-simple/Simple-Device'"
```
- update a provision watcher
```
level=DEBUG ts=2023-02-13T09:50:54.282282186Z app=core-metadata source=provisionwatcher.go:163 msg="ProvisionWatcher patched on DB successfully. Correlation-ID: 08da17e3-2bf8-4fc2-8800-952ea5d9c9e4 "
level=DEBUG ts=2023-02-13T09:50:54.283518303Z app=core-metadata source=notify.go:225 msg="Published the 'update' System Event for provisionwatcher 'provisionwatcher-1' to topic 'edgex/system-events/core-metadata/provisionwatcher/update/device-simple/Simple-Device'"
```
- delete a provision watcher
```
level=DEBUG ts=2023-02-13T09:54:02.068393209Z app=core-metadata source=notify.go:225 msg="Published the 'delete' System Event for provisionwatcher 'provisionwatcher-1' to topic 'edgex/system-events/core-metadata/provisionwatcher/delete/device-simple/Simple-Device'"
```
## New Dependency Instructions (If applicable)

2023-02-13 15:15 UTC, lenny-intel requested changes

2023-02-13 15:15 UTC, lenny-intel commented on internal/core/metadata/application/notify.go
> +		if pw, ok := dto.(dtos.ProvisionWatcher); ok {
Need error handling like above cases

2023-02-14 01:21 UTC, jinlinGuan commented on internal/core/metadata/application/notify.go
> +		if pw, ok := dto.(dtos.ProvisionWatcher); ok {
Added.

2023-02-14 01:44 UTC, cloudxxx8 commented
recheck

2023-02-14 01:48 UTC, lenny-intel approved these changes
LGTM

2023-02-14 02:07 UTC, lenny-intel commented
recheck

2023-02-14 06:08 UTC, cloudxxx8 commented
recheck

2023-02-14 06:15 UTC, cloudxxx8 commented
recheck

2023-02-14 07:28 UTC, merged