fix: Use Database Timeout setting defined in the configuration
edgexfoundry/edgex-go pull request #4503
Opened 2023-04-10 06:32 UTC by jinlinGuan

close #4486

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2023-04-10 06:48 UTC, cloudxxx8 submitted a review, later dismissed
LGTM

2023-04-10 19:16 UTC, lenny-intel requested changes

2023-04-10 19:16 UTC, lenny-intel commented on internal/pkg/db/redis/client.go
> +			retErr = fmt.Errorf("config.Timeout failed to parse: %v", err)
```suggestion
			retErr = fmt.Errorf("configured database timeout failed to parse: %v", err)
```

2023-04-11 01:14 UTC, jinlinGuan commented on internal/pkg/db/redis/client.go
> +			retErr = fmt.Errorf("config.Timeout failed to parse: %v", err)
updated

2023-04-11 02:01 UTC, lenny-intel approved these changes
LGTM

2023-04-11 05:24 UTC, merged