feat: Add GetSecret and RunTimeSecret metrics
edgexfoundry/edgex-go pull request #4556
Opened 2023-05-08 20:15 UTC by geraldzm

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

[go-mod-bootstrap](https://github.com/edgexfoundry/go-mod-bootstrap/pull/530)

## New Dependency Instructions (If applicable)

2023-05-08 20:28 UTC, bnevis-i commented on cmd/core-common-config-bootstrapper/res/configuration.yaml
> +        SecurityGetSecretDuration: true
Set to `false` once go.mod is upgraded to latest dev version.

2023-05-08 23:32 UTC, lenny-intel requested changes

2023-05-08 23:32 UTC, lenny-intel commented on cmd/core-common-config-bootstrapper/res/configuration.yaml
> +        securityRuntimeSecretTokenDuration: true
```suggestion
        SecurityRuntimeSecretTokenDuration: true
```

2023-05-09 01:02 UTC, bnevis-i requested changes
Need to bump the go-mod-bootstrap version.  Also should have just force pushed on top instead of creating the additional commit.

2023-05-09 01:22 UTC, bnevis-i approved these changes

2023-05-09 02:17 UTC, lenny-intel approved these changes
LGTM

2023-05-09 14:05 UTC, merged