fix: Initialize interval in the local time zone
edgexfoundry/edgex-go pull request #4595
Opened 2023-06-20 04:35 UTC by jackchenjc

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [ ] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2023-06-20 06:04 UTC, cloudxxx8 approved these changes
LGTM

2023-06-20 15:04 UTC, lenny-intel requested changes
Please amend your commit to have `fixes #4595`
Please add unit test that validates these changes (i.e. expand current test)
Please include how this is fully tested.

2023-06-21 09:42 UTC, jackchenjc commented
> Please amend your commit to have `fixes #4595` Please add unit test that validates these changes (i.e. expand current test) Please include in PR checklist how this is fully tested.

All comments have been addressed.

2023-06-22 01:37 UTC, cloudxxx8 approved these changes
LGTM

2023-06-28 01:09 UTC, merged