feat: add support-notification fuzzing test
edgexfoundry/edgex-go pull request #4744
Opened 2024-01-05 16:22 UTC by vli11

and update support-notifications.yaml file for fuzzing test

Closes: #4743

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
Just run the command `make fuzz-test-support-notifications`, you will observe the fuzzing test result for support-notifications on terminal and the detail result folder support-notifications created in fuzz_test/fuzz_results/

## New Dependency Instructions (If applicable)

2024-01-05 16:24 UTC, bnevis-i approved these changes

2024-01-05 16:37 UTC, jim-wang-intel submitted a review, later dismissed

2024-01-08 15:08 UTC, lenny-intel commented
recheck

2024-01-08 17:50 UTC, lenny-intel requested changes

2024-01-08 17:50 UTC, lenny-intel commented on Makefile
> +fuzz-test-support-notifications:
use short name like was done with core data and core command
```suggestion
fuzz-test-notifications:
```

2024-01-08 18:53 UTC, lenny-intel approved these changes
LGTM

2024-01-08 19:03 UTC, merged