feat: allow sending notifications to authenticated EdgeX endpoints
edgexfoundry/edgex-go pull request #4763
Opened 2024-02-23 04:03 UTC by jrtitus

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [X] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X] I am not introducing a new dependency (add notes below if you are)
- [ ] I have added unit tests for the new feature or bug fix (if not, why?)
- [X] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions

## New Dependency Instructions (If applicable)

2024-02-26 17:42 UTC, lenny-intel requested changes

2024-02-26 17:42 UTC, lenny-intel commented on internal/support/notifications/application/channel/sender.go
> +	}
`else` not needed since `injector` default value from `var` line is `nil`
```suggestion
	} 
```

2024-02-27 21:03 UTC, lenny-intel submitted a review, later dismissed
LGTM

2024-02-28 16:08 UTC, lenny-intel submitted a review, later dismissed

2024-03-04 10:01 UTC, cloudxxx8 approved these changes
LGTM

2024-03-04 10:01 UTC, merged